import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          style={{ backgroundColor: "#E0E0E0", minHeight: "100vh" }}
      >
          <header style={{
            position: "sticky",
            top: 0,
            zIndex: 50,
            backgroundColor: "#F6F3EE",
            borderBottom: "1px solid rgba(0,0,0,0.08)",
          }}>
            <nav style={{
              width: "100%",
              margin: 0,
              height: 56,
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              padding: "0 24px",
            }}>
              <div style={{ display: "flex", alignItems: "center", gap: 56 }}>
                <div
                  aria-label="Logo placeholder"
                  style={{
                    width: 32,
                    height: 32,
                    borderRadius: "50%",
                    backgroundColor: "#d9d9d9",
                    border: "1px solid rgba(0,0,0,0.1)",
                  }}
                />
                <div style={{ fontWeight: 600 }}>Khangla</div>
                <Link href="/" className="nav-link">
                  Homes
                </Link>
                <Link href="/home-owners" className="nav-link">
                  Home Owners
                </Link>
                <Link href="/bookings" className="nav-link">
                  Bookings
                </Link>
                <Link href="/about" className="nav-link">
                  About us
                </Link>
              </div>
              <div style={{ display: "flex", alignItems: "center", gap: 24 }}>
                {/* Right side controls */}
                <input
                  type="search"
                  placeholder="Search"
                  aria-label="Search"
                  style={{
                    width: 200,
                    maxWidth: "40vw",
                    height: 36,
                    padding: "0 12px",
                    borderRadius: 8,
                    border: "1px solid rgba(0,0,0,0.12)",
                    backgroundColor: "#C2C9CD",
                    outline: "none",
                  }}
                />
                <button
                  type="button"
                  aria-label="Open menu"
                  style={{
                    width: 36,
                    height: 36,
                    display: "inline-flex",
                    alignItems: "center",
                    justifyContent: "center",
                    borderRadius: 8,
                    border: "1px solid rgba(0,0,0,0.1)",
                    backgroundColor: "transparent",
                    cursor: "pointer",
                  }}
                >
                  <span
                    aria-hidden="true"
                    style={{
                      width: 18,
                      height: 12,
                      position: "relative",
                      display: "inline-block",
                    }}
                  >
                    <span style={{
                      position: "absolute",
                      top: 0,
                      left: 0,
                      right: 0,
                      height: 2,
                      backgroundColor: "#333",
                      borderRadius: 2,
                    }}></span>
                    <span style={{
                      position: "absolute",
                      top: 5,
                      left: 0,
                      right: 0,
                      height: 2,
                      backgroundColor: "#333",
                      borderRadius: 2,
                    }}></span>
                    <span style={{
                      position: "absolute",
                      bottom: 0,
                      left: 0,
                      right: 0,
                      height: 2,
                      backgroundColor: "#333",
                      borderRadius: 2,
                    }}></span>
                  </span>
                </button>
              </div>
            </nav>
          </header>
        {children}
      </body>
    </html>
  );
}
