export const styles = {
  page: {
    padding: 24,
    maxWidth: 1000,
    margin: "0 auto",
    background: "#F6F3EE",
    minHeight: "100vh",
    fontFamily: "system-ui, sans-serif",
  },
  header: {
    marginBottom: 24,
    paddingBottom: 12,
    borderBottom: "1px solid #C2C9CD",
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 900,
    color: "#547794",
  },
  headerSub: {
    fontSize: 14,
    color: "#6B7C88",
    marginTop: 4,
  },
  summaryGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 16,
    marginBottom: 24,
  },
  summaryCard: {
    background: "#FFFFFF",
    border: "1px solid #C2C9CD",
    borderRadius: 14,
    padding: 16,
    boxShadow: "0 8px 20px rgba(0,0,0,0.06)",
  },
  summaryLabel: {
    fontSize: 12,
    color: "#6B7C88",
  },
  summaryValue: {
    fontSize: 20,
    fontWeight: 900,
    marginTop: 6,
  },
  listCard: {
    background: "#FFFFFF",
    border: "1px solid #C2C9CD",
    borderRadius: 14,
    padding: 16,
    boxShadow: "0 8px 20px rgba(0,0,0,0.06)",
  },
  listHeader: {
    display: "flex",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  listTitle: {
    fontWeight: 800,
    fontSize: 15,
    color: "#1f2937",
  },
  listCount: {
    fontSize: 12,
    color: "#6B7C88",
  },
  listBody: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  row: {
    display: "grid",
    gridTemplateColumns: "2fr 1fr auto",
    gap: 12,
    alignItems: "center",
    border: "1px solid #E5E7EB",
    borderRadius: 12,
    padding: "12px 14px",
    background: "#FFFFFF",
    transition: "all 0.15s ease",
    cursor: "pointer",
  },
  rowTitle: {
    fontWeight: 700,
    fontSize: 14,
    color: "#1f2937",
  },
  rowSub: {
    fontSize: 12,
    color: "#6B7C88",
    marginTop: 2,
  },
  amountPill: {
    padding: "6px 12px",
    borderRadius: 999,
    border: "1px solid",
    fontSize: 13,
    fontWeight: 800,
    minWidth: 120,
    textAlign: "center",
  },
  statusPill: {
    padding: "6px 12px",
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 700,
    color: "#FFFFFF",
    minWidth: 80,
    textAlign: "center",
  },
};